services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: indotek_backend
    container_name: indotek_backend
    ports:
      - "8000:80"
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=indotek
      - DB_USERNAME=postgres
      - DB_PASSWORD=secret
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: indotek_frontend
    container_name: indotek_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: postgres:latest
    container_name: indotek_db
    environment:
      - POSTGRES_DB=indotek
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: